mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  database: prompt

siliconflow:
  api_key: sk-wplcytqmxykpttveojfecvdmcnpcohenxftpphvtfqmxpdtz
  base_url: https://api.siliconflow.cn/v1
  model: deepseek-ai/DeepSeek-V3.2-Exp

doubao:
  base_url: https://ark.cn-beijing.volces.com/api/v3
  model: doubao-seed-1-6-251015

